// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: manga.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MangaService_StreamSearch_FullMethodName     = "/mangahub.v1.MangaService/StreamSearch"
	MangaService_SearchManga_FullMethodName      = "/mangahub.v1.MangaService/SearchManga"
	MangaService_GetManga_FullMethodName         = "/mangahub.v1.MangaService/GetManga"
	MangaService_GetTrendingManga_FullMethodName = "/mangahub.v1.MangaService/GetTrendingManga"
	MangaService_AutoSuggest_FullMethodName      = "/mangahub.v1.MangaService/AutoSuggest"
	MangaService_HealthCheck_FullMethodName      = "/mangahub.v1.MangaService/HealthCheck"
)

// MangaServiceClient is the client API for MangaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MangaServiceClient interface {
	StreamSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MangaResponse], error)
	SearchManga(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*MangaResponse, error)
	// Extra RPCs currently implemented in service.go
	GetTrendingManga(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error)
	AutoSuggest(ctx context.Context, in *AutoSuggestRequest, opts ...grpc.CallOption) (*AutoSuggestResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type mangaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMangaServiceClient(cc grpc.ClientConnInterface) MangaServiceClient {
	return &mangaServiceClient{cc}
}

func (c *mangaServiceClient) StreamSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MangaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MangaService_ServiceDesc.Streams[0], MangaService_StreamSearch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, MangaResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MangaService_StreamSearchClient = grpc.ServerStreamingClient[MangaResponse]

func (c *mangaServiceClient) SearchManga(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MangaService_SearchManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*MangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MangaResponse)
	err := c.cc.Invoke(ctx, MangaService_GetManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) GetTrendingManga(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingResponse)
	err := c.cc.Invoke(ctx, MangaService_GetTrendingManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) AutoSuggest(ctx context.Context, in *AutoSuggestRequest, opts ...grpc.CallOption) (*AutoSuggestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoSuggestResponse)
	err := c.cc.Invoke(ctx, MangaService_AutoSuggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MangaService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MangaServiceServer is the server API for MangaService service.
// All implementations must embed UnimplementedMangaServiceServer
// for forward compatibility.
type MangaServiceServer interface {
	StreamSearch(*SearchRequest, grpc.ServerStreamingServer[MangaResponse]) error
	SearchManga(context.Context, *SearchRequest) (*SearchResponse, error)
	GetManga(context.Context, *GetMangaRequest) (*MangaResponse, error)
	// Extra RPCs currently implemented in service.go
	GetTrendingManga(context.Context, *TrendingRequest) (*TrendingResponse, error)
	AutoSuggest(context.Context, *AutoSuggestRequest) (*AutoSuggestResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMangaServiceServer()
}

// UnimplementedMangaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMangaServiceServer struct{}

func (UnimplementedMangaServiceServer) StreamSearch(*SearchRequest, grpc.ServerStreamingServer[MangaResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSearch not implemented")
}
func (UnimplementedMangaServiceServer) SearchManga(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchManga not implemented")
}
func (UnimplementedMangaServiceServer) GetManga(context.Context, *GetMangaRequest) (*MangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManga not implemented")
}
func (UnimplementedMangaServiceServer) GetTrendingManga(context.Context, *TrendingRequest) (*TrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingManga not implemented")
}
func (UnimplementedMangaServiceServer) AutoSuggest(context.Context, *AutoSuggestRequest) (*AutoSuggestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoSuggest not implemented")
}
func (UnimplementedMangaServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMangaServiceServer) mustEmbedUnimplementedMangaServiceServer() {}
func (UnimplementedMangaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMangaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MangaServiceServer will
// result in compilation errors.
type UnsafeMangaServiceServer interface {
	mustEmbedUnimplementedMangaServiceServer()
}

func RegisterMangaServiceServer(s grpc.ServiceRegistrar, srv MangaServiceServer) {
	// If the following call panics, it indicates UnimplementedMangaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MangaService_ServiceDesc, srv)
}

func _MangaService_StreamSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MangaServiceServer).StreamSearch(m, &grpc.GenericServerStream[SearchRequest, MangaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MangaService_StreamSearchServer = grpc.ServerStreamingServer[MangaResponse]

func _MangaService_SearchManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).SearchManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaService_SearchManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).SearchManga(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_GetManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaService_GetManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetManga(ctx, req.(*GetMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_GetTrendingManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).GetTrendingManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaService_GetTrendingManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).GetTrendingManga(ctx, req.(*TrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_AutoSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).AutoSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaService_AutoSuggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).AutoSuggest(ctx, req.(*AutoSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MangaService_ServiceDesc is the grpc.ServiceDesc for MangaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MangaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mangahub.v1.MangaService",
	HandlerType: (*MangaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchManga",
			Handler:    _MangaService_SearchManga_Handler,
		},
		{
			MethodName: "GetManga",
			Handler:    _MangaService_GetManga_Handler,
		},
		{
			MethodName: "GetTrendingManga",
			Handler:    _MangaService_GetTrendingManga_Handler,
		},
		{
			MethodName: "AutoSuggest",
			Handler:    _MangaService_AutoSuggest_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MangaService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSearch",
			Handler:       _MangaService_StreamSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "manga.proto",
}
