// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: manga.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_SERVING                   HealthStatus = 1
	HealthStatus_NOT_SERVING               HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"SERVING":                   1,
		"NOT_SERVING":               2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_manga_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_manga_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{0}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                       // FTS query
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                      // Max results (default 20)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                    // Pagination offset
	GenreIds      []string               `protobuf:"bytes,4,rep,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"` // matches req.GenreIds in service
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                     // Status filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetGenreIds() []string {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *SearchRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MangaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Genres         []*Genre               `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"` // matches pb.Genre in service
	CommentCount   int32                  `protobuf:"varint,7,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ChatCount      int32                  `protobuf:"varint,8,opt,name=chat_count,json=chatCount,proto3" json:"chat_count,omitempty"`
	WeeklyScore    int32                  `protobuf:"varint,9,opt,name=weekly_score,json=weeklyScore,proto3" json:"weekly_score,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,11,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MangaResponse) Reset() {
	*x = MangaResponse{}
	mi := &file_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaResponse) ProtoMessage() {}

func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaResponse.ProtoReflect.Descriptor instead.
func (*MangaResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{1}
}

func (x *MangaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MangaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MangaResponse) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *MangaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MangaResponse) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *MangaResponse) GetChatCount() int32 {
	if x != nil {
		return x.ChatCount
	}
	return 0
}

func (x *MangaResponse) GetWeeklyScore() int32 {
	if x != nil {
		return x.WeeklyScore
	}
	return 0
}

func (x *MangaResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MangaResponse) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{2}
}

func (x *Genre) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         []*MangaResponse       `protobuf:"bytes,1,rep,name=manga,proto3" json:"manga,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetManga() []*MangaResponse {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{4}
}

func (x *GetMangaRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type TrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{5}
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         []*MangaResponse       `protobuf:"bytes,1,rep,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingResponse) GetManga() []*MangaResponse {
	if x != nil {
		return x.Manga
	}
	return nil
}

type AutoSuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoSuggestRequest) Reset() {
	*x = AutoSuggestRequest{}
	mi := &file_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSuggestRequest) ProtoMessage() {}

func (x *AutoSuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSuggestRequest.ProtoReflect.Descriptor instead.
func (*AutoSuggestRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{7}
}

func (x *AutoSuggestRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AutoSuggestRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AutoSuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoSuggestResponse) Reset() {
	*x = AutoSuggestResponse{}
	mi := &file_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSuggestResponse) ProtoMessage() {}

func (x *AutoSuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSuggestResponse.ProtoReflect.Descriptor instead.
func (*AutoSuggestResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{8}
}

func (x *AutoSuggestResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=mangahub.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        int64                  `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_manga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_manga_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_manga_proto protoreflect.FileDescriptor

const file_manga_proto_rawDesc = "" +
	"\n" +
	"\vmanga.proto\x12\vmangahub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tgenre_ids\x18\x04 \x03(\tR\bgenreIds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x83\x03\n" +
	"\rMangaResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x06genres\x18\x06 \x03(\v2\x12.mangahub.v1.GenreR\x06genres\x12#\n" +
	"\rcomment_count\x18\a \x01(\x05R\fcommentCount\x12\x1d\n" +
	"\n" +
	"chat_count\x18\b \x01(\x05R\tchatCount\x12!\n" +
	"\fweekly_score\x18\t \x01(\x05R\vweeklyScore\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x0frelevance_score\x18\v \x01(\x02R\x0erelevanceScore\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa1\x01\n" +
	"\x0eSearchResponse\x120\n" +
	"\x05manga\x18\x01 \x03(\v2\x1a.mangahub.v1.MangaResponseR\x05manga\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\",\n" +
	"\x0fGetMangaRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\"'\n" +
	"\x0fTrendingRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"D\n" +
	"\x10TrendingResponse\x120\n" +
	"\x05manga\x18\x01 \x03(\v2\x1a.mangahub.v1.MangaResponseR\x05manga\"B\n" +
	"\x12AutoSuggestRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"7\n" +
	"\x13AutoSuggestResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions\"\x14\n" +
	"\x12HealthCheckRequest\"\x94\x01\n" +
	"\x13HealthCheckResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.mangahub.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime*K\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xdb\x03\n" +
	"\fMangaService\x12H\n" +
	"\fStreamSearch\x12\x1a.mangahub.v1.SearchRequest\x1a\x1a.mangahub.v1.MangaResponse0\x01\x12F\n" +
	"\vSearchManga\x12\x1a.mangahub.v1.SearchRequest\x1a\x1b.mangahub.v1.SearchResponse\x12D\n" +
	"\bGetManga\x12\x1c.mangahub.v1.GetMangaRequest\x1a\x1a.mangahub.v1.MangaResponse\x12O\n" +
	"\x10GetTrendingManga\x12\x1c.mangahub.v1.TrendingRequest\x1a\x1d.mangahub.v1.TrendingResponse\x12P\n" +
	"\vAutoSuggest\x12\x1f.mangahub.v1.AutoSuggestRequest\x1a .mangahub.v1.AutoSuggestResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.mangahub.v1.HealthCheckRequest\x1a .mangahub.v1.HealthCheckResponseB(Z&mangahub/internal/protocols/grpc/pb;pbb\x06proto3"

var (
	file_manga_proto_rawDescOnce sync.Once
	file_manga_proto_rawDescData []byte
)

func file_manga_proto_rawDescGZIP() []byte {
	file_manga_proto_rawDescOnce.Do(func() {
		file_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)))
	})
	return file_manga_proto_rawDescData
}

var file_manga_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_manga_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: mangahub.v1.HealthStatus
	(*SearchRequest)(nil),         // 1: mangahub.v1.SearchRequest
	(*MangaResponse)(nil),         // 2: mangahub.v1.MangaResponse
	(*Genre)(nil),                 // 3: mangahub.v1.Genre
	(*SearchResponse)(nil),        // 4: mangahub.v1.SearchResponse
	(*GetMangaRequest)(nil),       // 5: mangahub.v1.GetMangaRequest
	(*TrendingRequest)(nil),       // 6: mangahub.v1.TrendingRequest
	(*TrendingResponse)(nil),      // 7: mangahub.v1.TrendingResponse
	(*AutoSuggestRequest)(nil),    // 8: mangahub.v1.AutoSuggestRequest
	(*AutoSuggestResponse)(nil),   // 9: mangahub.v1.AutoSuggestResponse
	(*HealthCheckRequest)(nil),    // 10: mangahub.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 11: mangahub.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_manga_proto_depIdxs = []int32{
	3,  // 0: mangahub.v1.MangaResponse.genres:type_name -> mangahub.v1.Genre
	12, // 1: mangahub.v1.MangaResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 2: mangahub.v1.SearchResponse.manga:type_name -> mangahub.v1.MangaResponse
	2,  // 3: mangahub.v1.TrendingResponse.manga:type_name -> mangahub.v1.MangaResponse
	0,  // 4: mangahub.v1.HealthCheckResponse.status:type_name -> mangahub.v1.HealthStatus
	1,  // 5: mangahub.v1.MangaService.StreamSearch:input_type -> mangahub.v1.SearchRequest
	1,  // 6: mangahub.v1.MangaService.SearchManga:input_type -> mangahub.v1.SearchRequest
	5,  // 7: mangahub.v1.MangaService.GetManga:input_type -> mangahub.v1.GetMangaRequest
	6,  // 8: mangahub.v1.MangaService.GetTrendingManga:input_type -> mangahub.v1.TrendingRequest
	8,  // 9: mangahub.v1.MangaService.AutoSuggest:input_type -> mangahub.v1.AutoSuggestRequest
	10, // 10: mangahub.v1.MangaService.HealthCheck:input_type -> mangahub.v1.HealthCheckRequest
	2,  // 11: mangahub.v1.MangaService.StreamSearch:output_type -> mangahub.v1.MangaResponse
	4,  // 12: mangahub.v1.MangaService.SearchManga:output_type -> mangahub.v1.SearchResponse
	2,  // 13: mangahub.v1.MangaService.GetManga:output_type -> mangahub.v1.MangaResponse
	7,  // 14: mangahub.v1.MangaService.GetTrendingManga:output_type -> mangahub.v1.TrendingResponse
	9,  // 15: mangahub.v1.MangaService.AutoSuggest:output_type -> mangahub.v1.AutoSuggestResponse
	11, // 16: mangahub.v1.MangaService.HealthCheck:output_type -> mangahub.v1.HealthCheckResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_manga_proto_init() }
func file_manga_proto_init() {
	if File_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manga_proto_rawDesc), len(file_manga_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manga_proto_goTypes,
		DependencyIndexes: file_manga_proto_depIdxs,
		EnumInfos:         file_manga_proto_enumTypes,
		MessageInfos:      file_manga_proto_msgTypes,
	}.Build()
	File_manga_proto = out.File
	file_manga_proto_goTypes = nil
	file_manga_proto_depIdxs = nil
}
